"""Repeat guard (E2 + E4, Jake's 10/03 email): count the ask, not the run.

Overnight 10/02-10/03, 183 of 302 Worker runs lasted under a minute. A card asked Jake for a hands-on step, got
re-approved (phone, auto-approve, board wipe), and the Worker claimed it again and asked for the same step in new words.
Every approval writes jarvis:reset, which zeroes the 3-a-day cap, so the cap never stopped it.

This check runs inside ghq.claim() before the claim comment is posted. It uses no AI and no Claude usage:

  * Find the card's latest ask to Jake: a run that ended needs-jake, a "**Needs Jake:**" comment, or a To-Do step
    (jarvis:jake marker).
  * Since that ask, did anything change? Any one of these counts:
      - Jake answered or ticked the step on his To-Do page ("Jake on his To-Do page", "Jake approved the plan", ...)
      - a comment written by a person (any author not in JARVIS_BOT_LOGINS), e.g. Jake typing on GitHub; a Claude
        thread's status note (Claude Code footer) doesn't count unless it carries the marker below
      - an input the card was waiting on arrived ("Snooze condition met")
      - a comment carrying <!-- jarvis:changed --> (for any tool that fixes something on a card's behalf)
      - the card's text was edited after the ask (GitHub's lastEditedAt)
      - a file in the card's work folder is newer than the ask (when the Worker passes its folder)
  * Nothing changed -> the claim is refused, the card goes back to needs-jake with its To-Do step re-attached, and one
    comment says why. The approval tap does nothing; the step stays on Jake's To-Do list.

Approvals alone ("Approved via phone/board wipe/correction", "Auto-approved") never count as a change. Fails open: any
error lets the claim go ahead, so a guard bug can never stop the Worker.

    from repeatguard import unchanged_since_ask
    why = unchanged_since_ask(issue, comments, edited_at=..., folder=...)   # None = run it
"""
import json
import os
import re
from datetime import datetime, timezone

GUARD_MARK = '<!-- jarvis:repeatguard -->'
CHANGED_MARK = '<!-- jarvis:changed'
CLAUDE_FOOTER = '_Generated by [Claude Code]'
BOT_LOGINS = {s.strip().lower() for s in os.environ.get('JARVIS_BOT_LOGINS', 'clauderigassist-cell').split(',') if s.strip()}

RUNMETA_RE = re.compile(r'<!-- jarvis:runmeta (\{.*?\}) -->')
JAKE_RE = re.compile(r'<!-- jarvis:jake (\{.*?\}) -->', re.S)
JAKE_ACTION_PREFIXES = ('Jake on his To-Do page', 'Jake approved the plan', 'Jake asked on his To-Do', 'Jake: ',
                        'Jake replied', 'Jake answered')
CHANGE_PREFIXES = ('Snooze condition met',)
# Machine-written comments: Workers, the hub and scripts have posted under Jake's own login (10/02), so a comment from
# his login only counts as "Jake typed something" when it isn't one of these.
MACHINE_PREFIXES = ('<!--', '**Needs Jake', 'Claimed by', 'Snooze', 'Moved to', 'Board wipe', 'Closed via', '**Run on',
                    '**Progress', 'Tested in Docker', '**Tested in Docker', 'Filed for Jake', 'Loop net', 'Stopped after',
                    'Additions (', 'Released', 'Parked', '**On Jake', 'Spawned', 'Follow-up', 'FOLLOWUP')
APPROVAL_PREFIXES = ('Approved via', 'Auto-approved', 'Approved by', 'Re-approved')
FOLDER_SKIP = {'STATUS.md', 'run.log', 'claude-output.txt', 'prompt.txt'}
FOLDER_GRACE_S = 120   # files the run itself wrote just before its ask was posted


def _t(s):
    try:
        return datetime.fromisoformat((s or '').replace('Z', '+00:00'))
    except ValueError:
        return None


def _author(c):
    return ((c.get('user') or {}).get('login') or '').lower()


def is_ask(body):
    """True for a comment that hands the card to Jake."""
    if body.startswith('**Needs Jake:**') or JAKE_RE.search(body):
        return True
    m = RUNMETA_RE.search(body)
    if m:
        try:
            return json.loads(m.group(1)).get('outcome') == 'needs-jake'
        except ValueError:
            return False
    return False


def is_change(c):
    """True for a comment that means something moved since the ask (see module doc)."""
    body = (c.get('body') or '').lstrip()
    if GUARD_MARK in body:
        return False
    if CHANGED_MARK in body:
        return True
    if body.startswith(APPROVAL_PREFIXES):
        return False   # an approval is not a change (the phone hub posts these under Jake's own login)
    login = _author(c)
    if (login and login not in BOT_LOGINS and not login.endswith('[bot]') and CLAUDE_FOOTER not in body
            and not body.startswith(MACHINE_PREFIXES)):
        return True   # a person typed on the card (a Claude thread's status note has the footer and doesn't count)
    return (body.startswith(JAKE_ACTION_PREFIXES) or body.startswith(CHANGE_PREFIXES))


def ask_time(c):
    """When the ask was made. A run record's own `ended` time wins: with E8 the run record is the claim comment edited
    in place, so its created_at is when the run started."""
    m = RUNMETA_RE.search(c.get('body') or '')
    if m:
        try:
            ended = _t(json.loads(m.group(1)).get('ended'))
            if ended:
                return ended
        except ValueError:
            pass
    return _t(c.get('created_at'))


def last_ask(comments):
    """(index, time) of the latest ask, or (None, None)."""
    for i in range(len(comments) - 1, -1, -1):
        if is_ask(comments[i].get('body') or ''):
            return i, ask_time(comments[i])
    return None, None


def folder_changed(folder, since):
    if not folder or not since or not os.path.isdir(folder):
        return None
    cutoff = since.timestamp() + FOLDER_GRACE_S
    for root, dirs, files in os.walk(folder):
        dirs[:] = [d for d in dirs if not d.startswith(('.', '__'))]
        for f in files:
            if f in FOLDER_SKIP or f.endswith(('.bak', '.tmp', '.pyc')):
                continue
            try:
                if os.path.getmtime(os.path.join(root, f)) > cutoff:
                    return os.path.relpath(os.path.join(root, f), folder)
            except OSError:
                continue
    return None


def unchanged_since_ask(issue, comments, edited_at=None, folder=None):
    """None when the card may run. Otherwise a one-line reason: it already asked Jake and nothing changed since.

    issue: the GitHub issue (labels are read for `now`); comments: every comment, oldest first;
    edited_at: the issue's lastEditedAt (ISO) or None; folder: the card's work folder or None."""
    try:
        names = {(l.get('name') if isinstance(l, dict) else l) for l in issue.get('labels', [])}
        if 'now' in names:
            return None   # Jake typed it just now
        i, asked = last_ask(comments)
        if i is None or asked is None:
            return None   # never asked Jake: a normal first run
        for c in comments[i + 1:]:
            if is_change(c):
                return None
        e = _t(edited_at) if edited_at else None
        if e and e > asked:
            return None
        if folder_changed(folder, asked):
            return None
        when = asked.astimezone(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
        return f'asked Jake at {when} and nothing changed since (no answer, no ticked To-Do item, no edit, no new file)'
    except Exception:  # noqa: BLE001 - fail open
        return None


def last_step(comments):
    """The newest To-Do step dict on the card, or None (to put it back on Jake's list)."""
    for c in reversed(comments):
        m = JAKE_RE.search(c.get('body') or '')
        if m:
            try:
                return json.loads(m.group(1))
            except ValueError:
                return None
    return None


# ---------------------------------------------------------------------------- ghq glue

EDITED_Q = 'query($o:String!,$n:String!,$i:Int!){repository(owner:$o,name:$n){issue(number:$i){lastEditedAt}}}'


def edited_at(ghq, number):
    try:
        owner, name = ghq.REPO.split('/', 1)
        _, data, _ = ghq.request('POST', 'https://api.github.com/graphql',
                                 {'query': EDITED_Q, 'variables': {'o': owner, 'n': name, 'i': int(number)}})
        return (((data or {}).get('data') or {}).get('repository') or {}).get('issue', {}).get('lastEditedAt')
    except Exception:  # noqa: BLE001
        return None


def check_before_claim(ghq, number, issue, folder=None):
    """Call at the top of ghq.claim(), after the 'still approved?' check. True = go ahead and claim.
    False = the card was handed back to Jake unchanged (status needs-jake, To-Do step re-attached, one comment)."""
    if os.environ.get('JARVIS_REPEAT_GUARD', 'on') == 'off':
        return True
    try:
        comments = list(ghq.paged(ghq.repo_path(f'/issues/{number}/comments')))
        why = unchanged_since_ask(issue, comments, edited_at=edited_at(ghq, number), folder=folder)
        if not why:
            return True
        step = last_step(comments)
        ghq.set_status(number, 'needs-jake', extra_remove=[f'claimed:{m}' for m in ghq.MACHINES])
        ghq.comment(number, f'{GUARD_MARK}\nNot run again: this card {why}. The approval did nothing, and the step '
                            f'stays on Jake\'s To-Do list. Tick it, answer on the card, or edit the card and it runs.')
        if step and hasattr(ghq, 'jake_step'):
            step.pop('since', None)
            ghq.jake_step(number, step)   # an approval clears the step (jake_step_of), so put it back
        return False
    except Exception:  # noqa: BLE001 - fail open
        return True
