import json, os, time, tempfile
import repeatguard as rg

BOT = {'login': 'clauderigassist-cell'}
JAKE = {'login': 'flanneryjake'}


def c(t, body, user=BOT):
    return {'created_at': t, 'body': body, 'user': user}


ASK = c('2026-10-03T08:00:00Z', '<!-- jarvis:run -->\n<!-- jarvis:runmeta {"machine": "rig", "outcome": "needs-jake"} -->')
STEP = c('2026-10-03T08:00:05Z', '<!-- jarvis:jake {"place": "5060", "title": "Run add-startup-trigger.ps1"} -->\n**On Jake')
APPROVE = c('2026-10-03T08:10:00Z', 'Approved via phone at 2026-10-03T08:10:00+00:00\n<!-- jarvis:reset -->', JAKE)


def test_first_run_is_allowed():
    assert rg.unchanged_since_ask({'labels': []}, [c('2026-10-03T07:00:00Z', 'hi')]) is None


def test_approval_alone_is_refused():
    assert rg.unchanged_since_ask({'labels': []}, [ASK, STEP, APPROVE])


def test_board_wipe_and_review_notes_are_not_changes():
    notes = [c('2026-10-03T08:20:00Z', 'Board wipe 2026-10-03: the 5060 restarted'),
             c('2026-10-03T08:21:00Z', '<!-- jarvis:review claude -->\nNothing has changed'),
             c('2026-10-03T08:22:00Z', 'Approved via board wipe at x\n<!-- jarvis:reset -->')]
    assert rg.unchanged_since_ask({'labels': []}, [ASK, STEP, APPROVE] + notes)


def test_todo_tick_releases():
    tick = c('2026-10-03T08:09:00Z', 'Jake on his To-Do page: done', JAKE)
    assert rg.unchanged_since_ask({'labels': []}, [ASK, STEP, tick, APPROVE]) is None


def test_jake_typing_on_github_releases_but_claude_status_note_does_not():
    typed = c('2026-10-03T08:09:00Z', 'plugged the printer in', JAKE)
    assert rg.unchanged_since_ask({'labels': []}, [ASK, STEP, typed, APPROVE]) is None
    note = c('2026-10-03T08:09:00Z', '**Status (Claude):** looking\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_', JAKE)
    assert rg.unchanged_since_ask({'labels': []}, [ASK, STEP, note, APPROVE])
    fixed = c('2026-10-03T08:09:00Z', 'Fixed the path.\n<!-- jarvis:changed -->\n_Generated by [Claude Code]', JAKE)
    assert rg.unchanged_since_ask({'labels': []}, [ASK, STEP, fixed, APPROVE]) is None


def test_snooze_condition_met_releases():
    met = c('2026-10-03T08:09:00Z', 'Snooze condition met (file: `x`): back to approved')
    assert rg.unchanged_since_ask({'labels': []}, [ASK, STEP, met]) is None


def test_card_edit_after_ask_releases():
    assert rg.unchanged_since_ask({'labels': []}, [ASK, STEP, APPROVE], edited_at='2026-10-03T08:05:00Z') is None
    assert rg.unchanged_since_ask({'labels': []}, [ASK, STEP, APPROVE], edited_at='2026-10-03T07:05:00Z')


def test_new_file_in_card_folder_releases():
    with tempfile.TemporaryDirectory() as d:
        f = os.path.join(d, 'result.txt')
        open(f, 'w').write('x')
        asked = rg._t('2026-10-03T08:00:00Z').timestamp()
        os.utime(f, (asked + 3600, asked + 3600))
        assert rg.unchanged_since_ask({'labels': []}, [ASK, STEP, APPROVE], folder=d) is None
        os.utime(f, (asked + 30, asked + 30))   # written by the run itself, inside the grace window
        assert rg.unchanged_since_ask({'labels': []}, [ASK, STEP, APPROVE], folder=d)


def test_now_cards_always_run():
    assert rg.unchanged_since_ask({'labels': [{'name': 'now'}]}, [ASK, STEP, APPROVE]) is None


def test_fails_open_on_garbage():
    assert rg.unchanged_since_ask(None, None) is None


def test_real_histories_block_most_repeat_claims():
    from replay import replay
    here = os.path.dirname(os.path.abspath(__file__))
    for n, at_least in ((690, 5), (123, 19), (924, 12), (378, 5), (7, 7)):
        r = replay(json.load(open(os.path.join(here, 'fixtures', f'card-{n}.json'))))
        assert sum(1 for _, w in r if w) >= at_least, n
        assert r[0][1] is None   # the first claim of a card is never refused


class FakeGhq:
    REPO = 'o/r'
    MACHINES = ['homebase', 'rig']

    def __init__(self, comments, fail=False):
        self.comments, self.fail, self.calls = comments, fail, []

    def repo_path(self, s):
        return s

    def paged(self, path):
        if self.fail:
            raise RuntimeError('down')
        return iter(self.comments)

    def request(self, *a, **k):
        return 200, {'data': {'repository': {'issue': {'lastEditedAt': None}}}}, {}

    def set_status(self, n, status, extra_add=(), extra_remove=()):
        self.calls.append(('status', status))

    def comment(self, n, text, **k):
        self.calls.append(('comment', text))

    def jake_step(self, n, step):
        self.calls.append(('step', step['title']))


def test_check_before_claim_hands_back_and_reattaches_step():
    g = FakeGhq([ASK, STEP, APPROVE])
    assert rg.check_before_claim(g, 690, {'labels': []}) is False
    kinds = [k for k, _ in g.calls]
    assert kinds == ['status', 'comment', 'step'] and g.calls[0][1] == 'needs-jake'
    assert rg.GUARD_MARK in g.calls[1][1]


def test_check_before_claim_allows_and_fails_open():
    assert rg.check_before_claim(FakeGhq([c('2026-10-03T07:00:00Z', 'x')]), 1, {'labels': []}) is True
    assert rg.check_before_claim(FakeGhq([], fail=True), 1, {'labels': []}) is True
    os.environ['JARVIS_REPEAT_GUARD'] = 'off'
    try:
        assert rg.check_before_claim(FakeGhq([ASK, STEP, APPROVE]), 1, {'labels': []}) is True
    finally:
        del os.environ['JARVIS_REPEAT_GUARD']


def test_guard_comment_is_not_itself_an_ask_or_change():
    g = FakeGhq([ASK, STEP, APPROVE])
    rg.check_before_claim(g, 690, {'labels': []})
    body = g.calls[1][1]
    assert not rg.is_ask(body) and not rg.is_change({'body': body, 'user': BOT})
